version: "3.9"

networks:
  docker_project:

services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: "${APP_NAME}-server"
    ports:
      - "${APP_PORT}:80"
    working_dir: /var/www/html
    environment:
      - "DATABASE_URL=mysql://root:root@db_server:3306/${APP_NAME}?serverVersion=10.5"
    volumes:
      - ./htdocs:/var/www/html
      - ./docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
    depends_on:
      db_server:
        condition: service_healthy
    networks:
      - "${APP_NAME}"

  db_server:
    image: mariadb:10.5.9
    container_name: "${APP_NAME}-db"
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "${APP_NAME}"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 5
    networks:
      - "${APP_NAME}"

  db_admin:
    image: phpmyadmin/phpmyadmin:5
    container_name: "${APP_NAME}-db-admin"
    ports:
      - "${APP_DB_ADMIN_PORT}:80"
    environment:
      PMA_HOST: db_server
    depends_on:
      db_server:
        condition: service_healthy
    volumes:
      - db_admin_data:/var/www/html
    networks:
      - "${APP_NAME}"

  smtp_dev:
    image: mailhog/mailhog
    container_name: "${APP_NAME}-smtp-dev"
    logging:
      driver: "none"
    ports:
      - "${APP_SMTP_API_PORT}:1025"
      - "${APP_SMTP_ADMIN_PORT}:8025"
    restart: always
    networks:
      - "${APP_NAME}"

volumes:
  db_data:
  db_admin_data:
